steps:
  # Step 1: Build Docker image
  - id: build-docker-image
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${_IMAGE_TAG}'
      - '.'

  # Step 2: Push Docker image to Artifact Registry
  - id: push-docker-image
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}:${_IMAGE_TAG}'

  # Step 3: Conditional deploy to Kubernetes
  - id: deploy-kubernetes
    name: "google/cloud-sdk:latest" # Includes both gcloud and kubectl
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$_DEPLOY_TARGET" == "k8s" ]; then
          echo "Deploying to Kubernetes..."
        
          # Configure access to GKE cluster
          gcloud container clusters get-credentials ${_K8S_CLUSTER} --region ${_REGION} --project ${PROJECT_ID}
          
          # Verify cluster context
          kubectl config get-contexts

          # Apply Kubernetes manifests
          cd kubernetes || (echo "kubernetes folder not found!" && exit 1)
          ./k8s-deploy.sh ${_K8S_NAMESPACE} || (echo "Deployment script failed!" && exit 1)
        else
          echo "Deployment target is not Kubernetes. Skipping Kubernetes deployment."
        fi

substitutions:
  _REGION: europe-west4
  _IMAGE_NAME: europe-west4-docker.pkg.dev/driven-stage-457910-k8/my-docker-repo/my-node-server-simplified
  _IMAGE_TAG: latest
  _DEPLOY_TARGET: "k8s"  # Options: 'k8s', 'cloudrun', etc.
  _K8S_CLUSTER: "my-cluster"
  _K8S_NAMESPACE: "default"

timeout: '600s' # 10 minutes

options:
  logging: CLOUD_LOGGING_ONLY
