apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: europe-west4-docker.pkg.dev/driven-stage-457910-k8/my-repo/my-node-app:latest
          ports:
            - containerPort: 3000
