apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  labels:
    app: my-node-app
spec:
  type: LoadBalancer
  loadBalancerIP: 34.91.92.62
  selector:
    app: my-node-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
